"use strict";

const path = require("node:path");
const { spawnSync } = require("node:child_process");

const root = path.resolve(__dirname, "..");
const withoutSmoke = process.argv.includes("--without-smoke");
const syntaxFiles = [
  "scripts/check-all.js",
  "server.js",
  "database.js",
  "api/index.js",
  "lib/collection-export.js",
  "lib/collection-import.js",
  "lib/privacy-summary.js",
  "lib/archaeology.js",
  "lib/archaeology-backup.js",
  "lib/demo-safety.js",
  "lib/demo-seed.js",
  "lib/migrations.js",
  "lib/revision-backup.js",
  "lib/revision-database.js",
  "lib/revision-api.js",
  "lib/runtime-metadata.js",
  "lib/database-health.js",
  "lib/collection-health.js",
  "lib/collection-health-api.js",
  "lib/archive-http.js",
  "lib/archive-staging.js",
  "lib/archive-inspection-api.js",
  "lib/exhibition-curator.js",
  "lib/exhibition-database.js",
  "lib/exhibition-api.js",
  "lib/revisit-service.js",
  "lib/revisit-database.js",
  "lib/revisit-intent-database.js",
  "lib/revisit-api.js",
  "lib/time-calibration-service.js",
  "lib/time-calibration-database.js",
  "lib/time-calibration-api.js",
  "lib/clue-service.js",
  "lib/clue-backup.js",
  "lib/clue-database.js",
  "lib/clue-api.js",
  "lib/voice-policy.js",
  "lib/voice-format.js",
  "lib/voice-storage.js",
  "lib/voice-database.js",
  "lib/voice-api.js",
  "lib/voice-backup.js",
  "lib/capsule-service.js",
  "lib/capsule-database.js",
  "lib/capsule-api.js",
  "lib/offline-exhibit-api.js",
  "lib/request-security.js",
  "lib/time-isle-archive.js",
  "lib/media-format.js",
  "lib/media-policy.js",
  "lib/media-storage.js",
  "lib/media-database.js",
  "lib/media-evidence.js",
  "lib/media-similarity.js",
  "lib/exif-hints.js",
  "lib/media-backup.js",
  "lib/media-restore.js",
  "lib/media-api.js",
  "public/assets/portability.js",
  "public/assets/media-intelligence.js",
  "public/assets/media.js",
  "public/assets/media-evidence.js",
  "public/assets/media-compare.js",
  "public/assets/media-ocr.js",
  "public/assets/media-lab.js",
  "public/assets/exhibitions.js",
  "public/assets/revisit-intents.js",
  "public/assets/revisits.js",
  "public/assets/time-calibrations.js",
  "public/assets/revisions.js",
  "public/assets/clues.js",
  "public/assets/collection-health.js",
  "public/assets/voice.js",
  "public/assets/capsule-crypto.js",
  "public/assets/share-privacy.js",
  "public/assets/capsules.js",
  "public/assets/pwa.js",
  "public/sw.js",
  "public/assets/app.js"
];
const checks = [
  "scripts/frontend-check.js",
  "scripts/demo-safety-check.js",
  "scripts/request-security-check.js",
  "scripts/collection-import-check.js",
  "scripts/revision-database-check.js",
  "scripts/revision-backup-check.js",
  "scripts/memory-version-check.js",
  "scripts/collection-health-check.js",
  "scripts/database-health-check.js",
  "scripts/archive-stream-check.js",
  "scripts/archive-staging-check.js",
  "scripts/archive-inspection-check.js",
  "scripts/archaeology-check.js",
  "scripts/exhibition-check.js",
  "scripts/revisit-check.js",
  "scripts/revisit-intent-check.js",
  "scripts/revisit-intent-ui-check.js",
  "scripts/time-calibration-check.js",
  "scripts/time-calibration-ui-check.js",
  "scripts/clue-service-check.js",
  "scripts/clue-database-check.js",
  "scripts/clue-api-ui-check.js",
  "scripts/voice-format-check.js",
  "scripts/voice-storage-check.js",
  "scripts/voice-database-check.js",
  "scripts/voice-api-check.js",
  "scripts/voice-ui-check.js",
  "scripts/voice-backup-check.js",
  "scripts/capsule-service-check.js",
  "scripts/capsule-database-check.js",
  "scripts/capsule-api-check.js",
  "scripts/offline-exhibit-check.js",
  "scripts/capsule-ui-check.js",
  "scripts/pwa-check.js",
  "scripts/media-format-check.js",
  "scripts/media-storage-check.js",
  "scripts/media-api-check.js",
  "scripts/media-database-check.js",
  "scripts/media-evidence-check.js",
  "scripts/archive-check.js",
  "scripts/exif-hints-check.js",
  "scripts/media-similarity-check.js",
  "scripts/media-backup-check.js",
  "scripts/media-restore-check.js",
  "scripts/media-compare-check.js",
  "scripts/media-ocr-check.js",
  "scripts/media-lab-check.js",
  ...withoutSmoke ? [] : ["scripts/api-smoke.js"]
];

for (const file of syntaxFiles) run(["--check", file], `语法检查 ${file}`);
for (const file of checks) run([file], `回归检查 ${file}`);
console.log(withoutSmoke ? "Build checks passed." : "All project checks passed.");

function run(args, label) {
  const result = spawnSync(process.execPath, args, { cwd: root, stdio: "inherit", env: process.env });
  if (result.status === 0) return;
  console.error(`${label} 失败。`);
  process.exit(result.status || 1);
}
